# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'HelloWorld' do
 
pod 'AppCenter'


  # Pods for HelloWorld

  target 'HelloWorldTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'HelloWorldUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
